export default [
    {
        img: "expertteachers/1.jpg",
        fan: "Algebra",
        kun: "210",
        h4: "",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "",
        _id: "algebrateachers",
        title:"Algebra",
    },
    {
        img: "expertteachers/2.jpg",
        fan: "Fizika",
        kun: "210",
        h4: "Fizika uchun yangi Kurs",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "$165.00",
        _id: "fizikateachers",
        title:"Fizika",
        
    },
    {
        img: "expertteachers/3.jpg",
        fan: "Kimyo",
        kun: "210",
        h4: "Kimya uchun yangi Kurs",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "$165.00",
        _id: "kimyoteachers",
        title:"Kimyo",
      
    },
    {
        img: "expertteachers/4.jpg",
        fan: "Biologiya",
        kun: "102",
        h4: "Biologiya uchun yangi Kurs",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "$165.00",
        _id: "giologiyateachers",
        title:"Biologiya",
       
    },
    {
        img: "expertteachers/5.jpg",
        fan: "Geografiya",
        kun: "75",
        h4: "Geografiya uchun yangi Kurs",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "$165.00",
        _id: "geografiyateachers",
        title:"Geografiya",
       
    },
    {
        img: "expertteachers/6.jpg",
        fan: "Tarix",
        kun: "210",
        h4: "Tarix uchun yangi Kurs",
        p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, placeat, ipsa. Modi sed quibusdam vel autem fugit, eaque, iste. Excepturi fugit dignissimos suscipit dolor perferendis debitis magni sed, quia ab.",
        narxi: "$165.00",
        _id: "tarixteachers",
        title: "Tarix", 
    },
]