export default [
    {
        img: "blog-1.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Obuljon",
        date: "24.12.2022",
        commit: "1000",
        p:"",
        linc: "/news1",
        next: "/news2",
        prev: "/news6",
    },
    {
        img: "blog-2.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news2",
        next: "/news3",
        prev: "/news1",
    },
    {
        img: "blog-3.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news3",
        next: "/news4",
        prev: "/news2",
    },
    {
        img: "blog-4.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news4",
        next: "/news5",
        prev: "/news3",
    },
    {
        img: "blog-5.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news5",
        next: "/news6",
        prev: "/news4",
    },
    {
        img: "blog-6.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news6",
        next: "/news1",
        prev: "/news5",
    },
]