export default [
    {
        img: "blog-1.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Obuljon",
        date: "24.12.2022",
        commit: "1000",
        p:"",
        linc: "/news01",
        next: "/news02",
        prev: "/news06",
    },
    {
        img: "blog-2.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news02",
        next: "/news03",
        prev: "/news01",
    },
    {
        img: "blog-3.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news03",
        next: "/news04",
        prev: "/news02",
    },
    {
        img: "blog-4.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news04",
        next: "/news05",
        prev: "/news03",
    },
    {
        img: "blog-5.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news05",
        next: "/news06",
        prev: "/news04",
    },
    {
        img: "blog-6.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/news06",
        next: "/news01",
        prev: "/news05",
    },
]