export default [
    {
        img: "blog-1.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Obuljon",
        date: "24.12.2022",
        commit: "1000",
        p:"",
        linc: "/popularnews1",
        next: "/popularnews2",
        prev: "/popularnews6",
    },
    {
        img: "blog-2.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/popularnews2",
        next: "/popularnews3",
        prev: "/popularnews1",
    },
    {
        img: "blog-3.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/popularnews3",
        next: "/popularnews4",
        prev: "/popularnews2",
    },
    {
        img: "blog-4.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/popularnews4",
        next: "/popularnews5",
        prev: "/popularnews3",
    },
    {
        img: "blog-5.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/popularnews5",
        next: "/popularnews6",
        prev: "/popularnews4",
    },
    {
        img: "blog-6.jpg",
        h3: "Lorem ipsum dolor sit amet.",
        admin: "By Admin",
        date: "02 June 2016",
        commit: "0",
        p:"",
        linc: "/popularnews6",
        next: "/popularnews1",
        prev: "/popularnews5",
    },
]